title: "smoran-dev - Blog & Resume"
description: "Data Engineering, AI, Snowflake, Jetson tinkering, and notes."
url: "https://smoran-dev.github.io"
baseurl: ""
timezone: America/New_York

markdown: kramdown
kramdown:
  input: GFM

theme: minima
permalink: "/:categories/:title/"

header_pages:
  - blog.markdown
  - pages/resume.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

sass:
  style: compressed

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/smoran-dev" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/seanmoran5" }

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - log
  - tmp

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Sean Moran"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
