title: "SMORAN-DEV - Blog & Resume"
description: "Data Engineering, AI, Snowflake, Jetson tinkering, and notes."
url: "https://smoran-dev.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
permalink: "/:categories/:title/"

header_pages:
  - blog.markdown
  - pages/resume.md

plugins: # (alias: 'gems' also works on Jekyll 3.x)
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Minima theme tweaks
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/smoran-dev" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/seanemoran" }

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults (expanded mapping to avoid YAML inline edge cases)
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Sean Moran"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
